// Code generated by protoc-gen-go.
// source: service.proto
// DO NOT EDIT!

/*
Package task is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
*/
package task

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import task1 "."
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for TaskService service

type TaskServiceClient interface {
	Add(ctx context.Context, in *task1.TaskRequest, opts ...grpc.CallOption) (*task1.TaskResponse, error)
	List(ctx context.Context, in *task1.TaskRequest, opts ...grpc.CallOption) (*task1.TaskResponse, error)
}

type taskServiceClient struct {
	cc *grpc.ClientConn
}

func NewTaskServiceClient(cc *grpc.ClientConn) TaskServiceClient {
	return &taskServiceClient{cc}
}

func (c *taskServiceClient) Add(ctx context.Context, in *task1.TaskRequest, opts ...grpc.CallOption) (*task1.TaskResponse, error) {
	out := new(task1.TaskResponse)
	err := grpc.Invoke(ctx, "/task.TaskService/Add", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) List(ctx context.Context, in *task1.TaskRequest, opts ...grpc.CallOption) (*task1.TaskResponse, error) {
	out := new(task1.TaskResponse)
	err := grpc.Invoke(ctx, "/task.TaskService/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TaskService service

type TaskServiceServer interface {
	Add(context.Context, *task1.TaskRequest) (*task1.TaskResponse, error)
	List(context.Context, *task1.TaskRequest) (*task1.TaskResponse, error)
}

func RegisterTaskServiceServer(s *grpc.Server, srv TaskServiceServer) {
	s.RegisterService(&_TaskService_serviceDesc, srv)
}

func _TaskService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(task1.TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.TaskService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).Add(ctx, req.(*task1.TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(task1.TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.TaskService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).List(ctx, req.(*task1.TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TaskService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "task.TaskService",
	HandlerType: (*TaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _TaskService_Add_Handler,
		},
		{
			MethodName: "List",
			Handler:    _TaskService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 156 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x29, 0x49, 0x2c, 0xce, 0x96,
	0xe2, 0x02, 0x91, 0x10, 0x11, 0x29, 0x99, 0xf4, 0xfc, 0xfc, 0xf4, 0x9c, 0x54, 0xfd, 0xc4, 0x82,
	0x4c, 0xfd, 0xc4, 0xbc, 0xbc, 0xfc, 0x92, 0xc4, 0x92, 0xcc, 0xfc, 0xbc, 0x62, 0x88, 0xac, 0xd1,
	0x04, 0x46, 0x2e, 0xee, 0x90, 0xc4, 0xe2, 0xec, 0x60, 0x88, 0x29, 0x42, 0xf6, 0x5c, 0xcc, 0x8e,
	0x29, 0x29, 0x42, 0x82, 0x7a, 0x60, 0x13, 0x40, 0x32, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25,
	0x52, 0x42, 0xc8, 0x42, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x4a, 0x82, 0x4d, 0x97, 0x9f, 0x4c,
	0x66, 0xe2, 0x56, 0xe2, 0xd4, 0x2f, 0x33, 0xd4, 0x07, 0x49, 0x17, 0x0b, 0x39, 0x70, 0xb1, 0xf8,
	0x64, 0x16, 0x97, 0x90, 0x68, 0x82, 0x10, 0xc2, 0x84, 0x24, 0x36, 0xb0, 0xcb, 0x8c, 0x01, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x66, 0x02, 0xd6, 0x6c, 0xda, 0x00, 0x00, 0x00,
}
